Import('env')

env.QstrFeatureObject(source=['moductypes.c',
                              'modujson.c',
                              'modure.c',
                              'moduzlib.c',
                              'moduheapq.c',
                              'moduhashlib.c',
                              'modubinascii.c',
                              'machine_mem.c',
                              'modussl.c',
                              'modurandom.c',
                              'modwebsocket.c',
                              'fsusermount.c',
                              'vfs_fat.c',
                              'vfs_fat_ffconf.c',
                              'vfs_fat_diskio.c',
                              'vfs_fat_file.c',
                              'vfs_fat_lexer.c',
                              'vfs_fat_misc.c',
                              'moduos_dupterm.c'])
# TODO: review config option
env.QstrFeatureObject(source=['modussl.c'],
                      is_enabled=env['CONFIG'].MICROPYTHON_EXTMOD_PY_USSL)
